Algoritmo "Tabuada2"

Var
   vlr: inteiro

Inicio
    escreva("Entre com o valor para a TABUADA :: ")
    leia(vlr)
    escreval(vlr ," * 1 = ", vlr*1)
    escreval(vlr ," * 2 = ", vlr*2)
    escreval(vlr ," * 3 = ", vlr*3)
    escreval(vlr ," * 4 = ", vlr*4)
    escreval(vlr ," * 5 = ", vlr*5)
    escreval(vlr ," * 6 = ", vlr*6)
    escreval(vlr ," * 7 = ", vlr*7)
    escreval(vlr ," * 8 = ", vlr*8)
    escreval(vlr ," * 9 = ", vlr*9)
    escreval(vlr ," * 10 = ", vlr*10)

Fimalgoritmo